title: La Revoluzione
author: PolItKy
email: tbd
description: > # this means to ignore newlines until "baseurl:"
  This is a site. 
  It will appear in description for Google search results. 
  Also something about xml.

# social links
twitter_username: No. 
github_username:  PolItKy

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
